# Generated by Django 4.2 on 2024-12-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(upload_to='coffee_images/'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
