# Generated by Django 4.2 on 2024-12-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_coffee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=250, unique=True)),
                ('Phone', models.PositiveIntegerField(max_length=10)),
                ('Message', models.TextField()),
            ],
        ),
    ]
