# Generated by Django 4.2 on 2024-12-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Phone',
            field=models.PositiveIntegerField(),
        ),
    ]
