# Generated by Django 4.2 on 2024-12-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_contactus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
