# Generated by Django 4.2 on 2024-12-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_contactus_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Email',
            new_name='your_email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Phone',
            new_name='your_phone',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='Your_Name',
        ),
        migrations.AddField(
            model_name='contactus',
            name='your_name',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
